#!/usr/bin/env node
/**
 * Render the static site that GitHub Pages publishes at https://lunker.edycu.dev.
 *
 *   node scripts/build-site.mjs          write site/index.html, site/privacy.html,
 *                                        site/verify/index.html + site/verify/verify.js
 *   node scripts/build-site.mjs --check  exit 1 if either file is stale (CI)
 *
 * The landing page and privacy policy are authored in TypeScript next to the
 * Worker (worker/src/landing.ts, worker/src/routes/privacy.ts) because the
 * bite-times card is generated from the same schedule code the cron runs. This
 * script bundles those two modules with the esbuild that ships with wrangler and
 * writes their output, so the committed HTML can never drift from the code.
 * site/assets/ and site/pitch/ are hand-maintained files and are not touched.
 */
import { build } from '../worker/node_modules/esbuild/lib/main.js';
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const check = process.argv.includes('--check');

const dir = mkdtempSync(join(tmpdir(), 'lunker-site-'));
const entry = join(dir, 'entry.ts');
const out = join(dir, 'entry.mjs');
writeFileSync(
  entry,
  `export { renderLanding } from ${JSON.stringify(join(ROOT, 'worker/src/landing.ts'))};\n` +
    `export { PRIVACY_HTML } from ${JSON.stringify(join(ROOT, 'worker/src/routes/privacy.ts'))};\n` +
    `export { renderVerifyShell } from ${JSON.stringify(join(ROOT, 'worker/src/verify-render.ts'))};\n`,
);

try {
  await build({
    entryPoints: [entry],
    outfile: out,
    bundle: true,
    format: 'esm',
    platform: 'neutral',
    logLevel: 'error',
  });
  const { renderLanding, PRIVACY_HTML, renderVerifyShell } = await import(pathToFileURL(out).href);

  // The /verify page's browser script: the Worker's own renderer, bundled.
  const client = await build({
    entryPoints: [join(ROOT, 'site-src/verify-client.ts')],
    bundle: true,
    format: 'iife',
    platform: 'browser',
    target: 'es2019',
    write: false,
    legalComments: 'none',
    logLevel: 'error',
  });
  const verifyJs =
    '/* Generated by scripts/build-site.mjs from site-src/verify-client.ts. Do not edit. */\n' +
    client.outputFiles[0].text;

  const files = {
    'site/index.html': renderLanding(),
    'site/privacy.html': PRIVACY_HTML,
    'site/verify/index.html': renderVerifyShell(),
    'site/verify/verify.js': verifyJs,
  };
  const stale = [];
  for (const [rel, body] of Object.entries(files)) {
    const path = join(ROOT, rel);
    let current = null;
    try {
      current = readFileSync(path, 'utf8');
    } catch {
      /* missing counts as stale */
    }
    if (current === body) continue;
    if (check) stale.push(rel);
    else {
      mkdirSync(dirname(path), { recursive: true });
      writeFileSync(path, body);
      console.log(`wrote ${rel} (${body.length} bytes)`);
    }
  }
  if (check && stale.length) {
    console.error(`stale: ${stale.join(', ')} — run: node scripts/build-site.mjs`);
    process.exitCode = 1;
  } else if (check) {
    console.log('site/ is up to date');
  }
} finally {
  rmSync(dir, { recursive: true, force: true });
}
